"""add final_verdict column to request_logs

Revision ID: 1ccd024a325c
Revises: 33a7e9c8c8a4
Create Date: 2026-09-26 15:06:00.625398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccd024a325c'
down_revision: Union[str, Sequence[str], None] = '33a7e9c8c8a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('final_verdict', sa.String(length=20), nullable=False, server_default='safe'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'final_verdict')
    # ### end Alembic commands ###
